apiVersion: v1
kind: Service
metadata:
  name: cvapp-web-svc
  labels:
    app: cvapp-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: cvapp-web-port
  selector:
    app: cvapp-web
  type: LoadBalancer
