apiVersion: v1
kind: ConfigMap
metadata:
  name: cvapp-configmap
  namespace: app
data:
  #mongo: "mongodb://root:pass@cvapp-db-svc:27017"
  #api: "http://cvapp-api:5000/api/v1/"
  #api: "http://app.cvapplication.xyz:5000/api/v1/"


  api: "http://cvapp-api-svc.app.svc.cluster.local:5000/api/v1/"

 # /api/v1