apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvapp-web
  namespace: app
  labels:
    app: cvapp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvapp-web
  template:
    metadata:
      labels:
        app: cvapp-web
    spec:
      containers:
        - name: cvapp-web
          image: michalziaja/cvapp-web
          ports:
            - name: cvapp-web-port
              containerPort: 3000
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: cvapp-configmap
                  key: api
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: cvapp-configmap
                  key: api_port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: cvapp-web-svc
  namespace: app
  labels:
    app: cvapp-web
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #   service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: cvapp-web-port
  selector:
    app: cvapp-web
  type: ClusterIP