apiVersion: v1
kind: ConfigMap
metadata:
  name: cvapp-configmap
  namespace: app
data:
  mongo: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@cvapp-db:27017"
  api: "cvapp-api"
  api_port: "5000"