apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvapp-api
  namespace: app
  labels:
    app: cvapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvapp-api
  template:
    metadata:
      labels:
        app: cvapp-api
    spec:
      containers:
        - name: cvapp-api
          image: michalziaja/cvapp-api:53
          ports:
            - name: cvapp-api-port
              containerPort: 5000
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cvapp-secret
                  key: jwt-key
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cvapp-secret
                  key: jwt-ref-key
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cvapp-secret
                  key: db-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cvapp-secret
                  key: db-pass
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: cvapp-configmap
                  key: mongo
      # initContainers:
      #   - name: init-cvapp
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup cvapp-db; do echo waiting for mydb; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: cvapp-api
  namespace: app
  labels:
    app: cvapp-api
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: cvapp-api-port
  selector:
    app: cvapp-api
  type: ClusterIP
