name: CvApp Destroy

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: "Host IP"
        required: true
env:
    # credentials for deployment to AWS
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # S3 bucket for the terraform state. 
    BUCKET_TF_STATE: ${{ secrets.BUCKET_TF }}
    AWS_REGION: eu-central-1
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:    
  delete_eks:
    name: "Delete EKS cluster"
    runs-on: ubuntu-latest
    needs: terraform
    
    defaults:
      run:
        shell: bash
    steps:      
      
      - name: AWS Configure
        uses: appleboy/ssh-action@v1.0.3
        id: aws_configure
        with:
          host: ${{ github.event.inputs.enviroment }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
              #sudo chmod +x install.sh
              #./install.sh
              #aws s3api list-buckets
              echo "HELLO"
 
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
